---
- name: this playbook install packages
  hosts: webservers
  become: true
  tasks:
  - name: start httpd service
    service:
      name: httpd
      state: stopped

  - name: uninstall httpd
    yum:
      name: httpd
      state: removed
