---
- name: this playbook install packages
  hosts: all
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: uninstall httpd
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"
      
  - name: stop apache2 service
    systemd:
      name: apache2
      state: stopped
      enabled: yes
    when: ansible_os_family == "Debian"

  - name: stop apache2 service
    systemd:
      name: apache2
      state: stopped
      enabled: yes
    when: ansible_os_family == "Debian"
